### ISSUE TITLE
Invalid private gathering message causes minor error cascade

### ISSUE THREAD

**Issue by m4gpi** [ssbc/scuttle-gathering#4]
On starting Patchbay, it beings to load, then throws this nasty lil error after streaming through the first few messages.

```
TypeError: Cannot destructure property `thread` of 'undefined' or 'null'.
    at getBacklinks (/home/kyphae/projects/patchbay/node_modules/scuttle-gathering/gathering/async/get.js:24:39)
    at /home/kyphae/projects/patchbay/node_modules/scuttle-gathering/lib/get-backlinks.js:10:41
    at server.get (/home/kyphae/projects/patchbay/node_modules/scuttle-gathering/gathering/async/get.js:21:27)
    at Object._requests.(anonymous function) (/home/kyphae/projects/patchbay/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/home/kyphae/projects/patchbay/node_modules/packet-stream/index.js:151:26)
    at PacketStream.write (/home/kyphae/projects/patchbay/node_modules/packet-stream/index.js:134:41)
    at /home/kyphae/projects/patchbay/node_modules/muxrpc/pull-weird.js:56:15
    at /home/kyphae/projects/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/kyphae/projects/patchbay/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/kyphae/projects/patchbay/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:39:14)
    at more (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:55:13)
    at Function.reader.read (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:99:7)
    at Object.cb (/home/kyphae/projects/patchbay/node_modules/packet-stream-codec/index.js:104:16)
    at drain (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:39:14)
    at more (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:55:13)
```

https://github.com/ssbc/scuttle-gathering/blob/89668bd3829a11844f76450a35bebba85a29611b/gathering/async/get.js#L20

After changing to...

```js
      getBacklinks(server)(gathering, (err, msgs) => {
        if (err) return cb(err)
        const { thread, backlinks } = msgs
```

Our true error is revealed...

```
Error: getBacklinks requires a valid gathering message
    at /home/kyphae/projects/patchbay/node_modules/scuttle-gathering/lib/get-backlinks.js:10:44
    at server.get (/home/kyphae/projects/patchbay/node_modules/scuttle-gathering/gathering/async/get.js:21:27)
    at Object._requests.(anonymous function) (/home/kyphae/projects/patchbay/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/home/kyphae/projects/patchbay/node_modules/packet-stream/index.js:151:26)
    at PacketStream.write (/home/kyphae/projects/patchbay/node_modules/packet-stream/index.js:134:41)
    at /home/kyphae/projects/patchbay/node_modules/muxrpc/pull-weird.js:56:15
    at /home/kyphae/projects/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/kyphae/projects/patchbay/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/kyphae/projects/patchbay/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:39:14)
    at more (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:55:13)
    at Function.reader.read (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:99:7)
    at Object.cb (/home/kyphae/projects/patchbay/node_modules/packet-stream-codec/index.js:104:16)
    at drain (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:39:14)
    at more (/home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:55:13)
    at /home/kyphae/projects/patchbay/node_modules/pull-reader/index.js:66:9
```

Here's the offending message:

```js
{
  key: '%D3gDqywusDqmcvmvkvNtL51LGgE+u490EPxMszNOj3w=.sha256',
  value: {
     previous: '%PbdqQKbfTbUtnBU5bfJPUFlhaOFY5RkipYMBBfCyf74=.sha256',
     sequence: 13677,
     author: '@NeB4q4Hy9IiMxs5L08oevEhivxW+/aDu/s/0SkNayi0=.ed25519',
     timestamp: 1540006986748,
     hash: 'sha256',
     content: ...
     signature: ...
  }
}
```

An MMT private gathering... :eye:

**Comment by m4gpi** [comment]
It looks like this has been resolved... it would appear I was a numpty and didn't bump my dependencies...
